spring:
  application:
    name: roomservice

  data:
    mongodb:
      database: roomservice
      port: '27017'
      host: localhost

logging:
  level:
    root: INFO
    com.sunlon.roomservice: DEBUG